export const categories = [
  "house",
  "apartment",
  "land",
  "flat",
  "villa",
  "office",
  "shop",
];
export const provinces = [
  "Koshi",
  "Madhesh",
  "Bagmati",
  "Gandaki",
  "Lumbini",
  "Sudurpashchim",
  "Karnali",
];
export const features = [
  "Earthquake resistant",
  "Marble",
  "Parquet",
  "CCTV",
  "Drainage",
  "Solar",
  "Garden",
  "Parking",
  "Drinking water",
  "Balcony",
  "Reserve tank",
  "Lawn",
  "Terrace",
  "Well",
  "Boring water",
  "Gazebo",
  "Attic",
  "Fireplace",
  "Heating",
  "Video door",
  "Bathtub",
  "Basement",
  "Staff quarters",
];
export const furnishings = [
  "Fridge",
  "Sofa",
  "Air conditioning",
  "Water purifier",
  "Washing machine",
  "TV",
  "Microwave",
  "Power backup",
  "Iron",
  "Modular kitchen",
  "Internet",
  "Closet",
  "Bed",
  "Dining table",
  "Dressing table",
];
export const rooms = [
  "Dining room",
  "Bedroom",
  "Bathroom",
  "Staff room",
  "Living room",
  "Storage",
  "Prayer room",
  "Guest room",
  "Laundry",
  "Pantry",
  "Family room",
  "Study",
  "Master bedroom",
  "Drawing room",
  "Kitchen",
  "Shutter/shop space",
];
export const directions = [
  "South",
  "North",
  "East",
  "West",
  "South-east",
  "South-west",
  "North-east",
  "North-west",
];
export const roadTypes = [
  "Blacktopped",
  "Dhalan",
  "Paved",
  "Gravelled",
  "Soil stabilized",
  "Alley",
];
export const landmarkCategories = [
  "Administrative offices",
  "Bank & finance",
  "Schools & colleges",
  "Hospital",
  "Religious site",
  "Mart",
];
export const categoryLabel = (value) =>
  ({ office: "Office space", shop: "Shop space", flat: "Flat" })[value] ||
  value?.charAt(0).toUpperCase() + value?.slice(1);
